name: Trigger auto deployment for album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/album-api-AutoDeployTrigger-4672427f-e24f-4844-af0a-0666fc6e27d8.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca20fa77c664acr.azurecr.io
          registryUsername: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}
          containerAppName: album-api
          resourceGroup: rg-lab6-cloud
          imageToBuild: ca20fa77c664acr.azurecr.io/album-api:${{ github.sha }}
          
            

     

